### ISSUE TITLE
Refactor Point from an F on Code Climate

### ISSUE THREAD

**Issue by duncanmalashock** [duncanmalashock/ivan#10]
https://codeclimate.com/repos/5590faabe30ba052da00607c/Point

- Clipping may want to be extracted into a separate class.
- Some of the C-flavored parts of the Cohen-Sutherland algorithm could be refactored for readability.

**Comment by a-leung** [comment]
this is the dream, but in reality, there's parts of [rails](http://github.com/rails/rails) that score an [F](https://codeclimate.com/github/rails/rails/code?q=rating%3AF)...

don't worry about it too much. :wink:

**Comment by duncanmalashock** [comment]
@a-leung hehe, thanks for the encouragement. I'm not taking Code Climate's grades as gospel (and the specific duplication and similarities that Code Climate found seem a little naive), but I do think the Point class has too many responsibilities right now– there's room for improvement.
